pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
  - name: ask to fix commit message
    conditions:
      - check-failure=Semantic Pull Request
      - -closed
    actions:
        comment:
          message: |
            Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org).
            Please adjust title before merge.
  - name: merge when all requested reviews are valid
    conditions:
      - "#approved-reviews-by>=1"
    actions:
        merge:
          method: merge
